<?php
declare(strict_types=1);
if (!isset($renderAdminView)) { require __DIR__ . '/../app/bootstrap.php'; (new App\Controllers\AdminController())->customers(); return; }
require __DIR__ . '/../includes/admin-header.php';
?>
<section class="admin-page-heading"><div><p class="eyebrow">Customer management</p><h1>Khách hàng</h1><p>Xem thông tin, doanh số, điểm thưởng, phân quyền và trạng thái tài khoản.</p></div></section>
<form class="admin-filters"><input name="q" value="<?=h($q)?>" placeholder="Tìm theo tên, email hoặc số điện thoại"><button class="admin-secondary">Tìm</button><a class="admin-secondary" href="customers.php">Xóa lọc</a></form>
<section class="admin-card"><header class="admin-card-header"><div><h2>Danh sách tài khoản</h2><p><?=count($users)?> tài khoản</p></div></header><div class="admin-table-wrap"><table class="admin-data-table"><thead><tr><th>Người dùng</th><th>Liên hệ</th><th>Đơn hàng</th><th>Chi tiêu</th><th>Điểm</th><th>Quyền</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><?php foreach($users as $user):?><tr><td><strong><?=h($user['full_name'])?></strong><small>#<?=(int)$user['id']?> · Tham gia <?=admin_date($user['created_at'])?></small></td><td><?=h($user['email'])?><small><?=h($user['phone']?:'Chưa có SĐT')?></small></td><td><?=(int)$user['order_count']?></td><td><?=admin_money($user['spent'])?></td><td><strong><?=number_format((int)$user['loyalty_points'],0,',','.')?></strong></td><td><span class="admin-status <?=h($user['role'])?>"><?=h(admin_status_label($user['role']))?></span></td><td><span class="admin-status <?=h($user['status'])?>"><?=h(admin_status_label($user['status']))?></span></td><td><?php if((int)$user['id']===(int)$admin['id']):?><small>Tài khoản hiện tại</small><?php else:?><div class="admin-actions"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="role"><input type="hidden" name="user_id" value="<?=(int)$user['id']?>"><input type="hidden" name="role" value="<?=$user['role']==='admin'?'customer':'admin'?>"><button type="submit"><?=$user['role']==='admin'?'Gỡ admin':'Cấp admin'?></button></form><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="status"><input type="hidden" name="user_id" value="<?=(int)$user['id']?>"><input type="hidden" name="status" value="<?=$user['status']==='active'?'disabled':'active'?>"><button class="<?=$user['status']==='active'?'danger':''?>" type="submit"><?=$user['status']==='active'?'Khóa':'Mở khóa'?></button></form></div><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require __DIR__ . '/../includes/admin-footer.php'; ?>
