<?php
declare(strict_types=1);
if (!isset($renderAdminView)) { require __DIR__ . '/../app/bootstrap.php'; (new App\Controllers\AdminController())->order(); return; }
require __DIR__ . '/../includes/admin-header.php';
?>
<section class="admin-page-heading"><div><p class="eyebrow">Order detail</p><h1><?=h($order['order_number'])?></h1><p>Tạo lúc <?=admin_date($order['created_at'],true)?>.</p></div><a class="admin-secondary" href="orders.php">← Danh sách đơn</a></section>
<div class="admin-grid"><div><section class="admin-card"><header class="admin-card-header"><div><h2>Sản phẩm trong đơn</h2><p><?=count($items)?> dòng sản phẩm</p></div></header><?php if($items):?><div class="admin-table-wrap"><table class="admin-data-table"><thead><tr><th>Sản phẩm</th><th>Đơn giá</th><th>Số lượng</th><th>Thành tiền</th></tr></thead><tbody><?php foreach($items as $item):?><tr><td><strong><?=h($item['product_name'])?></strong><small><?=h($item['sku'])?></small></td><td><?=admin_money($item['unit_price'])?></td><td><?=(int)$item['quantity']?></td><td><strong><?=admin_money($item['line_total'])?></strong></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="admin-empty">Đơn chưa có chi tiết sản phẩm.</div><?php endif;?></section>
<section class="admin-card"><header class="admin-card-header"><div><h2>Thông tin giao hoa</h2></div></header><div class="admin-kpi-list"><div><span>Người nhận</span><strong><?=h($order['customer_name'])?> · <?=h($order['customer_phone'])?></strong></div><div><span>Email</span><strong><?=h($order['customer_email']?:'Chưa có')?></strong></div><div><span>Địa chỉ</span><strong><?=h($order['delivery_address'])?></strong></div><div><span>Ngày giao</span><strong><?=$order['delivery_date']?admin_date($order['delivery_date']):'Chưa hẹn'?></strong></div><div><span>Ghi chú</span><strong><?=nl2br(h($order['note']?:'Không có'))?></strong></div></div></section></div>
<aside><form class="admin-form-card" method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><div class="admin-form-grid"><div class="admin-field full"><label>Trạng thái đơn</label><select name="status"><?php foreach(['pending','confirmed','preparing','shipping','completed','cancelled'] as $value):?><option value="<?=$value?>" <?=$order['status']===$value?'selected':''?>><?=h(admin_status_label($value))?></option><?php endforeach;?></select></div><div class="admin-field full"><label>Thanh toán</label><select name="payment_status"><?php foreach(['unpaid','paid','refunded'] as $value):?><option value="<?=$value?>" <?=$order['payment_status']===$value?'selected':''?>><?=h(admin_status_label($value))?></option><?php endforeach;?></select><small>Điểm chỉ được cộng khi đơn hoàn thành và đã thanh toán.</small></div></div><div class="admin-form-actions"><button class="admin-primary" type="submit">Cập nhật đơn</button></div></form><section class="admin-card"><header class="admin-card-header"><div><h2>Tổng thanh toán</h2></div></header><div class="admin-kpi-list"><div><span>Phương thức</span><strong><?=h(admin_status_label($order['payment_method']))?></strong></div><?php if($order['payment_method']==='bank_transfer'):$bank=shop_config()['bank_transfer'];?><div><span>Ngân hàng</span><strong><?=h($bank['bank_name'])?> · <?=h($bank['account_number'])?></strong></div><div><span>Chủ tài khoản</span><strong><?=h($bank['account_name'])?></strong></div><div><span>Nội dung chuyển khoản</span><strong><?=h($order['order_number'])?></strong></div><?php endif;?><?php if($order['payment_method']==='momo'):?><div><span>Mã giao dịch MoMo</span><strong><?=h($order['payment_reference']?:'Chưa có')?></strong></div><div><span>Kết quả MoMo</span><strong><?= $order['momo_result_code'] === null ? 'Chưa có' : (int)$order['momo_result_code'] ?><?= $order['momo_message'] ? ' · '.h($order['momo_message']) : '' ?></strong></div><?php endif;?><div><span>Tạm tính</span><strong><?=admin_money($order['subtotal'])?></strong></div><div><span>Phí giao</span><strong><?=admin_money($order['shipping_fee'])?></strong></div><div><span>Điểm đã dùng</span><strong><?=(int)$order['points_used']?> điểm (-<?=admin_money($order['points_discount'])?>)</strong></div><div><span>Điểm được cộng</span><strong><?=(int)$order['points_earned']?> điểm</strong></div><div><span>Tổng cộng</span><strong style="color:var(--admin-rose);font-size:18px"><?=admin_money($order['total_amount'])?></strong></div></div></section></aside></div>
<?php require __DIR__ . '/../includes/admin-footer.php'; ?>
