<?php
declare(strict_types=1);
if (!isset($renderAdminView)) { require __DIR__ . '/../app/bootstrap.php'; (new App\Controllers\AdminController())->orders(); return; }
require __DIR__ . '/../includes/admin-header.php';
?>
<section class="admin-page-heading"><div><p class="eyebrow">Order management</p><h1>Đơn hàng</h1><p>Theo dõi thông tin giao hoa, thanh toán và tiến độ xử lý.</p></div></section>
<form class="admin-filters"><input name="q" value="<?=h($q)?>" placeholder="Tìm mã đơn, tên hoặc số điện thoại"><select name="status"><option value="">Mọi trạng thái</option><?php foreach(['pending','confirmed','preparing','shipping','completed','cancelled'] as $value):?><option value="<?=$value?>" <?=$status===$value?'selected':''?>><?=h(admin_status_label($value))?></option><?php endforeach;?></select><button class="admin-secondary">Lọc</button><a class="admin-secondary" href="orders.php">Xóa lọc</a></form>
<section class="admin-card"><header class="admin-card-header"><div><h2>Danh sách đơn</h2><p><?=count($orders)?> đơn hàng</p></div></header><?php if($orders):?><div class="admin-table-wrap"><table class="admin-data-table"><thead><tr><th>Đơn hàng</th><th>Khách hàng</th><th>Giao hàng</th><th>Tổng tiền</th><th>Thanh toán</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><?php foreach($orders as $order):?><tr><td><strong><?=h($order['order_number'])?></strong><small><?=admin_date($order['created_at'],true)?></small></td><td><?=h($order['customer_name'])?><small><?=h($order['customer_phone'])?></small></td><td><?=h($order['delivery_date']?admin_date($order['delivery_date']):'Chưa hẹn')?></td><td><strong><?=admin_money($order['total_amount'])?></strong><?php if((int)$order['points_earned']>0):?><small>+<?=(int)$order['points_earned']?> điểm</small><?php endif;?></td><td><strong><?=h(admin_status_label($order['payment_method']))?></strong><small><span class="admin-status <?=h($order['payment_status'])?>"><?=h(admin_status_label($order['payment_status']))?></span></small></td><td><span class="admin-status <?=h($order['status'])?>"><?=h(admin_status_label($order['status']))?></span></td><td><div class="admin-actions"><a href="order.php?id=<?=(int)$order['id']?>">Chi tiết</a><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=(int)$order['id']?>"><select name="status" style="height:29px;border:1px solid var(--admin-line);font-size:7px"><?php foreach(['pending','confirmed','preparing','shipping','completed','cancelled'] as $value):?><option value="<?=$value?>" <?=$order['status']===$value?'selected':''?>><?=h(admin_status_label($value))?></option><?php endforeach;?></select><button type="submit">Lưu</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="admin-empty">Chưa có đơn hàng nào.</div><?php endif;?></section>
<?php require __DIR__ . '/../includes/admin-footer.php'; ?>
