<?php require dirname(__DIR__, 3) . '/includes/auth-header.php'; ?>
<main class="account-main page-shell">
  <?php if ($flashMessage): ?><div class="auth-notice <?= h($flashMessage['type']) ?> account-flash"><?= h($flashMessage['message']) ?></div><?php endif; ?>
  <section class="account-hero"><div><p class="eyebrow">My flower account</p><h1>Xin chào, <?= h($user['full_name']) ?>.</h1><p>Một góc nhỏ để bạn quản lý tài khoản, đơn hoa và điểm thưởng.</p></div><span class="role-badge <?= $user['role'] === 'admin' ? 'admin' : '' ?>"><?= $user['role'] === 'admin' ? 'Quản trị viên' : 'Khách hàng' ?></span></section>
  <section class="loyalty-banner"><div><p class="eyebrow">Linh Florist Rewards</p><h2><?= number_format((int) ($user['loyalty_points'] ?? 0), 0, ',', '.') ?> điểm</h2><p>Cứ <?= admin_money(shop_config()['loyalty_vnd_per_point']) ?> tiền hàng nhận 1 điểm sau khi đơn hoàn thành và thanh toán.</p></div><span>Điểm thưởng</span></section>
  <section class="account-grid">
    <article class="account-panel profile-panel"><div class="panel-heading"><div><p class="eyebrow">Thông tin cá nhân</p><h2>Hồ sơ của bạn</h2></div><span class="profile-initial"><?= h(mb_strtoupper(mb_substr($user['full_name'],0,1))) ?></span></div><dl class="profile-list"><div><dt>Họ và tên</dt><dd><?= h($user['full_name']) ?></dd></div><div><dt>Email</dt><dd><?= h($user['email']) ?></dd></div><div><dt>Số điện thoại</dt><dd><?= h($user['phone'] ?: 'Chưa cập nhật') ?></dd></div><div><dt>Ngày tham gia</dt><dd><?= !empty($user['created_at']) ? h(date('d/m/Y',strtotime($user['created_at']))) : '-' ?></dd></div></dl></article>
    <article class="account-panel order-panel"><div class="panel-heading"><div><p class="eyebrow">Đơn hoa gần đây</p><h2><?= $recentOrders ? 'Lịch sử đặt hoa' : 'Chưa có đơn hàng' ?></h2></div><span class="panel-icon">♡</span></div><?php if ($recentOrders): ?><div class="account-order-list"><?php foreach ($recentOrders as $order): ?><div><span><strong><?= h($order['order_number']) ?></strong><small><?= h(admin_date($order['created_at'],true)) ?> · <?= h(admin_status_label($order['payment_method'])) ?></small></span><span><strong><?= h(admin_money($order['total_amount'])) ?></strong><small><?= h(admin_status_label($order['status'])) ?> · <?= h(admin_status_label($order['payment_status'])) ?></small><?php if ((int)$order['points_used'] > 0): ?><small>Đã dùng <?= (int)$order['points_used'] ?> điểm (-<?= h(admin_money($order['points_discount'])) ?>)</small><?php endif; ?><?php if ((int)$order['points_earned'] > 0): ?><small>+<?= (int)$order['points_earned'] ?> điểm</small><?php endif; ?></span></div><?php endforeach; ?></div><?php else: ?><p>Các đơn hoa của bạn sẽ xuất hiện tại đây sau khi đặt hàng.</p><?php endif; ?><a class="auth-primary-link" href="index.html#products"><?= $recentOrders ? 'Đặt thêm hoa' : 'Khám phá hoa tươi' ?></a></article>
    <article class="account-panel loyalty-history-panel"><div class="panel-heading"><div><p class="eyebrow">Lịch sử điểm</p><h2>Điểm thưởng gần đây</h2></div><span class="panel-icon">+</span></div><?php if ($loyaltyHistory): ?><div class="account-order-list"><?php foreach ($loyaltyHistory as $entry): ?><?php $sign=$entry['type']==='redeem'?'-':'+';$label=['earn'=>'Cộng từ đơn hàng','redeem'=>$entry['status']==='reversed'?'Đã hoàn lại':'Đã sử dụng','refund'=>'Hoàn do hủy đơn'][$entry['type']]??$entry['description']; ?><div><span><strong><?= h($entry['order_number']) ?></strong><small><?= h($entry['description']) ?> · <?= h(admin_date($entry['created_at'], true)) ?></small></span><span><strong class="points-<?= h($entry['type']) ?>"><?= $sign ?><?= (int)$entry['points'] ?> điểm</strong><small><?= h($label) ?></small></span></div><?php endforeach; ?></div><?php else: ?><p>Điểm cộng, sử dụng và hoàn lại sẽ xuất hiện tại đây.</p><?php endif; ?></article>
    <article class="account-panel account-actions-panel"><div><p class="eyebrow">Lối tắt</p><h2>Quản lý tài khoản</h2></div><div class="account-actions"><?php if ($user['role']==='admin'): ?><a class="admin-entry" href="admin/index.php"><span>✦</span><div><strong>Trang quản trị</strong><small>Quản lý sản phẩm, đơn hàng và khách hàng</small></div><b>→</b></a><?php endif; ?><a href="index.html"><span>⌂</span><div><strong>Về cửa hàng</strong><small>Tiếp tục xem các mẫu hoa</small></div><b>→</b></a><form method="post" action="logout.php"><?= csrf_field() ?><button type="submit"><span>↗</span><div><strong>Đăng xuất</strong><small>Kết thúc phiên đăng nhập hiện tại</small></div><b>→</b></button></form></div></article>
  </section>
</main>
<?php require dirname(__DIR__, 3) . '/includes/auth-footer.php'; ?>
